### PR TITLE
Add script that runs lint and tests

### LINKED ISSUE #32: `npm lint` doesn't run on Travis
When looking at the [log for the last successful](https://s3.amazonaws.com/archive.travis-ci.org/jobs/103650204/log.txt) master build, it looks like `npm run lint` never occurs.

### PR DESCRIPTION
**Pull request by nerdbeere**
fixes #32

### CODE REVIEW

**Comment by nerdbeere** [comment]
I still need to find a way to run this new script on travis instead of the default (`npm run test`)

**Comment by mitchhentges** [comment]
For the sake of nomenclature, is `test-all` really a good term? I mean, it's not like it runs more tests than `test`. The difference is linting.

Maybe make it a script called `ci-build` which runs `npm run build && npm run test && npm run lint`?

**Comment by mitchhentges** [comment]
Perhaps in `travis.yml`, add:
`script: npm run test-all` or `script npm run ci-build`
(I'm looking at https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step)

**Comment by nerdbeere** [comment]
You're right about the naming. Never thought about that. We always called it `test-all`.
Does `test-ci` makes sense for you?

**Comment by mitchhentges** [comment]
Yeah, I think that `test-ci` is pretty awesome. :+1:

**Pull request merged**
